添加 PandaGL 的 border 部分。
lc-soft/LCUI pull request #262
Opened 2021-09-18 08:35 UTC by GregoryLi0

Changes proposed in this pull request:
- Add border part of PandaGL

@lc-soft

2021-09-18 09:59 UTC, lc-soft requested changes

2021-09-18 09:59 UTC, lc-soft commented on include/PandaGL/types.h
> +    PD_STYPE_NONE,
这些代码还没删除吗？

2021-09-18 09:59 UTC, lc-soft commented on include/PandaGL/types.h
> +    PD_STYLE_VALUE_FLEX_START,
大部分枚举都用不到，background、shadow、border 的代码要用的话，应该分别给它们定义个 enum 枚举。

2021-09-18 09:59 UTC, lc-soft commented on include/PandaGL/types.h
> +        pd_canvas_t *val_image;
这块代码也一样，需要删除

2021-09-18 09:59 UTC, lc-soft commented on include/PandaGL/util/linkedlist.h
> + * Copyright to be defined
你的代码的版权声明也补全一下

2021-09-18 09:59 UTC, lc-soft commented on lib/PandaGL/xmake.lua
> +    add_files("src/*.c")
`add_files("src/**.c")` 就可以了

2021-09-18 09:59 UTC, lc-soft commented on xmake.lua
>          "lcui-platform",
需要删掉 `lcui-paint` 依赖。

2021-09-18 09:59 UTC, lc-soft commented on xmake.lua
> +    add_headerfiles("include/PandaGL/PandaGL/**/*.h")
不需要加 includedirs 和 headerfiles 的配置。lib 目录下的所有库的头文件都应该放在 `LCUI/` 目录中。

2021-09-18 09:59 UTC, lc-soft commented on lib/ui/src/widget_border.c
> +	border.top.width = style->border.top.width;
把 `style->border` 的数据类型替换成你的 `pd_border_t` 就能直接复制使用了，不用写下面这么多赋值代码。

2021-09-19 01:54 UTC, GregoryLi0 commented on xmake.lua
>          "lcui-platform",
现在PandaGL 的 line background boxshadow还没有添加到项目里。等到这三个添加到项目中就会删除lcui-paint依赖

2021-09-20 06:28 UTC, lc-soft requested changes

2021-09-20 06:28 UTC, lc-soft commented on include/PandaGL.h
> +
头文件不需要复制到 include 里。

在 xmake.lua 里将 `lib/pandaGL/include` 添加到头文件目录就可以了。

2021-09-20 06:28 UTC, lc-soft commented on lib/PandaGL/src/draw/border.c
> +double Sqrt( double dNum )
用标准库的 sqrt()

2021-09-20 06:28 UTC, lc-soft commented on lib/PandaGL/src/canvas.c
> +void pd_context_create(pd_context_t* context_ptr){
所有代码都用 clang-format 格式化一遍，LCUI 源码根目录有 clang-format 配置文件。

2021-09-29 05:35 UTC, closed without merging