UTIL: replace util by yutil
lc-soft/LCUI pull request #264
Opened 2021-09-21 14:49 UTC by yidianyiko

待办：

 - [ ] 更新 LCUI 的 xmake.lua，添加头文件包含路径和相关配置
- [ ] 替换旧 util 的头文件包含代码，例如：`#include <LCUI/util.h>`
- [ ] 替换旧 util 模块相关数据结构和函数调用代码，例如：`LinkedList` `Dict_Create`
  - [ ] 替换 timer
  - [ ] 替换 dict
  - [ ] 替换 linkedlist
  - [ ] 替换 rbtree
  - [ ] 替换 math
  - [ ] 替换 time
  - [ ] 替换 logger
- [ ] 删除旧 util 模块的构建配置和相关代码
- [ ] `helloworld` 运行正常，无闪退、卡顿、崩溃等问题
- [ ] `run-tests` 运行正常，通过所有测试

2021-09-21 15:05 UTC, yidianyiko commented
目前可以在 win 和 linux 上编译 lcui 、run-tests、helloworld，但执行存在问题。
（以下问题同时在两个平台上存在）
**存在问题及进度：**
1. 替换完所有函数后进行编译存在问题如下：
  - `LCUI_Color RGB()` 与 系统 `RGB`存在冲突，编译时总是编译为系统库函数 `RGB`，问题可能出在 <LCUI/graph.h> 下的 
 ```c
/* 解除RGB宏 */
#ifdef YUTIL_TEST_RGB
#undef YUTIL_TEST_RGB
#endif
```
并未按照顺序编译。
**解决方案：**
先暂时使用 YUTIL_TEST_RGB 替代 RGB ，可以顺利编译。

2. 执行 xmake run run-tests 后会在 test settings 处中断：
经过定位，发现
```c
// LCUI/lib/ui/src/widget_style.c
static size_t LCUI_LoadCSSBlock(LCUI_CSSParserContext ctx, const char *str)
{
	size_t size = 0;
	ctx->cur = str;
	while (*ctx->cur && size < ctx->buffer_size) {
		ctx->parsers[ctx->target].parse(ctx);
		++ctx->cur;
		++size;
	}
	return size;
}
```
每次执行这个循环时，当 `*ctx->cur` = 0x20 后程序就会中断。
解决方案：
目前还没有头绪，因为该文件并未涉及到函数替换，我将重新查看替换的文件和编译顺序是否存在问题。

2021-09-21 15:05 UTC, yidianyiko commented
目前可以在 win 和 linux 上编译 lcui 、run-tests、helloworld，但执行存在问题。
（以下问题同时在两个平台上存在）
**存在问题及进度：**
1. 替换完所有函数后进行编译存在问题如下：
  - `LCUI_Color RGB()` 与 系统 `RGB`存在冲突，编译时总是编译为系统库函数 `RGB`，问题可能出在 <LCUI/graph.h> 下的 
 ```c
/* 解除RGB宏 */
#ifdef YUTIL_TEST_RGB
#undef YUTIL_TEST_RGB
#endif
```
并未按照顺序编译。
**解决方案：**
先暂时使用 YUTIL_TEST_RGB 替代 RGB ，可以顺利编译。

2. 执行 xmake run run-tests 后会在 test settings 处中断：
经过定位，发现
```c
// LCUI/lib/ui/src/widget_style.c
static size_t LCUI_LoadCSSBlock(LCUI_CSSParserContext ctx, const char *str)
{
	size_t size = 0;
	ctx->cur = str;
	while (*ctx->cur && size < ctx->buffer_size) {
		ctx->parsers[ctx->target].parse(ctx);
		++ctx->cur;
		++size;
	}
	return size;
}
```
每次执行这个循环时，当 `*ctx->cur` = 0x20 后程序就会中断。
解决方案：
目前还没有头绪，因为该文件并未涉及到函数替换，我将重新查看替换的文件和编译顺序是否存在问题。

2021-09-22 02:41 UTC, lc-soft requested changes

2021-09-22 02:41 UTC, lc-soft commented on include/LCUI/gui/widget_base.h
> +#include <LCUI/util/keywords.h>
不用把 yutil 的头文件复制到 util 目录里，所有用到 yutil 的地方都改成 `#include <yutil.h>` 包含你的头文件。xmake.lua 中追加 `lib/yutil/include` 为头文件包含路径。

2021-09-22 02:41 UTC, lc-soft commented on include/LCUI/graph.h
> +#ifdef YUTIL_TEST_RGB
这代码有用吗？难不成 `YUTIL_TEST_RGB` 会重定义？原来的代码是为了解除系统库头文件中定义的 RGB 宏，避免 RGB 函数与 RGB 宏冲突。

2021-09-22 02:41 UTC, lc-soft commented on lib/paint/src/background.c
> +			rect.width = y_round(rect.width * scale);
`y_round` 这命名看不出与标准库的 round 有什么区别，请验证直接用标准库的 `round()` 是否可行。

2021-09-22 02:41 UTC, lc-soft commented on lib/platform/src/linux/linux_x11display.c
> +	list_for_each(node, &x11.surfaces)
`list_for_each()` 这块代码在编辑器里显示正常吗？以前我在 VisualStudio 里看这类代码时显示不正常，像是没正确识别出代码语法，后面都改用 `for (list_each(node, list))` 这种写法了。

2021-09-22 02:41 UTC, lc-soft commented on lib/ui/src/widget_tree.c
> +	list_clear_data(&w->children, Widget_OnDestroy);
关于 `list_clear_data()` 的命名，我在用的时候常常需要查看函数原型才知道哪个函数不会释放 node，你觉得是否有更好的命名能解决这问题？

2021-09-22 08:34 UTC, lc-soft commented
> 每次执行这个循环时，当 *ctx->cur = 0x20 后程序就会中断。

你需要先处理内存访问越界问题，因为它会导致其它代码块执行异常。

2021-09-23 01:02 UTC, yidianyiko commented
**进度**
已完成：已解决 rbtree_delete 报错。
待解决：strpool 中的 dict_add 引起的内存泄漏，暂时怀疑是新旧代码混用产生的问题。

2021-09-23 01:20 UTC, yidianyiko commented on lib/ui/src/widget_tree.c
> +	list_clear_data(&w->children, Widget_OnDestroy);
list 中涉及到删除和清除的有以下几个
```c
#define list_clear(list, func) list_clear_ex(list, func, 1)
#define list_clear_data(list, func) list_clear_ex(list, func, 0)

void list_clear_ex(list_t *list, void (*on_destroy)(void *), int free_node)
{
	list_node_t *prev, *node;
	node = list->tail.prev;
	list->head.next = NULL;
	list->tail.prev = NULL;
	list->length = 0;
	while (node && node != &list->head) {
		prev = node->prev;
		node->prev = NULL;
		node->next = NULL;
		if (node->data && on_destroy) {
			on_destroy(node->data);
		}
		if (free_node) {
			free(node);
		}
		node = prev;
	}
}

void list_delete_node(list_t *list, list_node_t *node)
{
	list_unlink(list, node);
	node->data = NULL;
	free(node);
	node = NULL;
}

void list_delete_by_pos(list_t *list, size_t pos)
{
	list_node_t *node = list_get_node_by_pos(list, pos);
	list_delete_node(list, node);
}

void list_node_free(list_node_t *node)
{
	free(node);
}

```
其中会`**_delete_**()`、`list_clear()`都会释放 node，
只有 `list_clear_data()`不会释放 node，我建议用`list_free()` 或者 `list_shutdown()`替代  `list_clear()`。
或者使用 `creat\destroy()` 代替 `list_init()\list_clear()`

2021-09-23 01:21 UTC, yidianyiko commented on lib/ui/src/widget_tree.c
> +	list_clear_data(&w->children, Widget_OnDestroy);
list 中涉及到删除和清除的有以下几个
```c
#define list_clear(list, func) list_clear_ex(list, func, 1)
#define list_clear_data(list, func) list_clear_ex(list, func, 0)

void list_clear_ex(list_t *list, void (*on_destroy)(void *), int free_node)
{
	list_node_t *prev, *node;
	node = list->tail.prev;
	list->head.next = NULL;
	list->tail.prev = NULL;
	list->length = 0;
	while (node && node != &list->head) {
		prev = node->prev;
		node->prev = NULL;
		node->next = NULL;
		if (node->data && on_destroy) {
			on_destroy(node->data);
		}
		if (free_node) {
			free(node);
		}
		node = prev;
	}
}

void list_delete_node(list_t *list, list_node_t *node)
{
	list_unlink(list, node);
	node->data = NULL;
	free(node);
	node = NULL;
}

void list_delete_by_pos(list_t *list, size_t pos)
{
	list_node_t *node = list_get_node_by_pos(list, pos);
	list_delete_node(list, node);
}

void list_node_free(list_node_t *node)
{
	free(node);
}

```
其中会`**_delete_**()`、`list_clear()`都会释放 node，
只有 `list_clear_data()`不会释放 node，我建议用`list_free()` 或者 `list_shutdown()`替代  `list_clear()`。
或者使用 `creat\destroy()` 代替 `list_init()\list_clear()`

2021-09-23 01:24 UTC, yidianyiko commented on lib/platform/src/linux/linux_x11display.c
> +	list_for_each(node, &x11.surfaces)
我使用的编译器 vscode 和 vs2019 并未报错，而且 linux 中相关代码实现也是 `list_for_each()` ，但既然后期都使用 `for (list_each(node, list))`这种写法，那我建议替换的时候统一成后者。

2021-09-23 02:53 UTC, yidianyiko commented on lib/paint/src/background.c
> +			rect.width = y_round(rect.width * scale);
`round()`在 C89 和 C99 中的定义有区别，可能会造成使用不同标准的编译器的执行结果不同，为避免可能的错误，建议还是保留 `y_round()`。
> C89的规则是，如果任何一个操作数是负数，那么除法的结果可以向上或向下舍入。
> C99中，它保证被截断为0。
**参阅：**
https://stackoverflow.com/questions/50068627/what-is-the-behavior-of-c89-with-respect-to-integer-division-of-two-negative-num

2021-09-23 05:31 UTC, lc-soft requested changes

2021-09-23 05:31 UTC, lc-soft commented on lib/paint/src/background.c
> +			rect.width = y_round(rect.width * scale);
y_round 返回值是 int，应该在函数名上体现，建议更名为 `y_iround`，或去掉它里面的 int 转换然后把所有调用代码改成 `(int)y_round(xxxx)`

2021-09-23 11:28 UTC, yidianyiko commented on include/LCUI/timer.h
> +LCUI_API int lcui_add_timeout(long int n_ms, timer_callback callback,
好的

2021-09-23 11:29 UTC, yidianyiko commented on lib/paint/src/background.c
> +			rect.width = y_round(rect.width * scale);
好的，我将更新命名为 `y_iround`

2021-09-24 02:46 UTC, lc-soft commented on lib/platform/src/linux/linux_x11display.c
> +	list_for_each(node, &x11.surfaces)
不是报错，是代码编辑器没有正确高亮代码。

2021-09-24 02:50 UTC, lc-soft commented on lib/ui/src/widget_tree.c
> +	list_clear_data(&w->children, Widget_OnDestroy);
用 `list_destroy_without_node()` 命名怎样？一看就知道不会释放 node。

2021-09-24 03:09 UTC, yidianyiko commented on lib/ui/src/widget_tree.c
> +	list_clear_data(&w->children, Widget_OnDestroy);
好的，那我将改名如下:
`list_init` -> `list_create`
`list_clear` -> `list_destroy`
`list_clear_data` -> `list_destroy_without_node`

2021-09-27 11:06 UTC, lc-soft requested changes

2021-09-27 12:38 UTC, yidianyiko commented on include/LCUI/timer.h
> +LCUI_API void lcui_timer_list_create();
好的👌。

2021-09-28 02:58 UTC, merged