Gregory/panda gl
lc-soft/LCUI pull request #265
Opened 2021-09-25 03:05 UTC by GregoryLi0

- lib/paint 目录内代码及相关调用代码的重命名
- 添加 PandaGL 优化文档

@lc-soft

2021-09-26 09:36 UTC, lc-soft requested changes
在此 PR 合并后，建议再完成以下任务：

- 绘制函数的第一个参数都改为 `pd_context_t* ctx`
- 绘制函数命名风格改为：`pd_do_something`，例如：将 `pd_border_paint` 重命名为 `pd_paint_border`
- 将宏改为 INLINE 内联函数

2021-09-26 09:36 UTC, lc-soft commented on include/LCUI/font/textlayer.h
> +	pd_bool_t enable_style_tag;    /**< 是否使用文本样式标签 */
你应该只改 lib/paint 里的 `LCUI_BOOL`，其它地方的不用改。

2021-09-26 09:36 UTC, lc-soft commented on include/LCUI/graph.h
> +#define graph_set_pixel(G, X, Y, C)                                        \
改成 `pd_graph_set_pixel`， 其它的也一样

2021-09-26 09:36 UTC, lc-soft commented on include/LCUI/graph.h
> +LCUI_API void pd_graph_copy(pd_canvas_t *des, const pd_canvas_t *src);
函数名与数类型对不上，到底是叫 graph 还是 canvas ？

2021-09-26 09:36 UTC, lc-soft commented on include/LCUI/gui/css_fontstyle.h
> +	pd_style_value white_space;
为什么要改到 LCUI_StyleValue？我一个月前的代码评论被你无视了？应该保持原有命名。

再补充个文档来介绍如何让图形库不依赖 `LCUI_StyleValue` 和 `LCUI_StyleType` 吧。

![image](https://user-images.githubusercontent.com/1730073/134801434-78f4b42c-64fe-453d-bc20-f8c3a74e7cca.png)

![image](https://user-images.githubusercontent.com/1730073/134801463-ca534dfb-1fdc-4ea4-bdcd-0f72850200fb.png)

![image](https://user-images.githubusercontent.com/1730073/134801505-3559191a-564b-465e-bca7-fda5f41a6276.png)

2021-09-26 09:36 UTC, lc-soft commented on include/LCUI/gui/css_library.h
> +	pd_style sheet;
`LCUI_Style` 是 css 库提供的类型，不属于图形库，不应该改这个，保持原有命名。

2021-09-26 09:36 UTC, lc-soft commented on include/LCUI/gui/css_library.h
> +	S->sheet[NAME].type = PD_STYPE_##TYPE, \
修改建议同上。

2021-09-26 09:36 UTC, lc-soft commented on docs/border优化方案.md
> +- 在 border_paint 中，获得更新后的 buffer 像素矩阵缓存。三个角落的像素值，对 buffer 中数据根据位置进行水平翻转、竖直翻转等操作，写回入 canvas 中。
这种方法需要一个临时缓存，那在绘制时进行坐标变换是否可行？如果可行，请写出坐标变换算法。

2021-09-26 09:36 UTC, lc-soft commented on docs/pd_context_t 改进方案.md
> +由于 pd_context_t 的更改，在 graph 中也有一些函数需要更改。比如 pd_graph_get_valid_rect 需要更改传入参数为 pd_context_t\*，返回 pd_context_t.rect，或者直接使用 pd_context_t.rect 代替此函数；graph_horiz_flip_rgb 等函数需要将传入参数从 pd_canvas_t\* 更改为 pd_c
直接使用 `pd_context_t.rect` 即可

2021-09-27 02:21 UTC, GregoryLi0 commented on include/LCUI/graph.h
> +LCUI_API void pd_graph_copy(pd_canvas_t *des, const pd_canvas_t *src);
已修改

2021-09-27 02:22 UTC, GregoryLi0 commented on include/LCUI/graph.h
> +#define graph_set_pixel(G, X, Y, C)                                        \
已修改。现在对于.h中向外暴露的函数用pd_为前缀，对于.c中内部使用的函数没有用前缀

2021-09-27 02:22 UTC, GregoryLi0 commented on include/LCUI/font/textlayer.h
> +	pd_bool_t enable_style_tag;    /**< 是否使用文本样式标签 */
已修改。目前在 type.h 中定义了LCUI_BOOL 和 pd_bool

2021-09-27 03:00 UTC, GregoryLi0 commented on docs/border优化方案.md
> +- 在 border_paint 中，获得更新后的 buffer 像素矩阵缓存。三个角落的像素值，对 buffer 中数据根据位置进行水平翻转、竖直翻转等操作，写回入 canvas 中。
是可行的。在上一版的PanndaGL中，已经使用此方法成功进行绘制。但这种方法有一个缺陷：开辟缓存和两次赋值可能对性能有一些影响。

以绘制右上角border传回数据为例
`
// 将数据写回 canvas
    for (int y = 0; y < rect.height; ++y) {
        dst_color_ptr = pd_canvas_get_pixel_pointer(&canvas_buffer, 0, y);
        src_color_ptr = pd_canvas_get_pixel_pointer(&canvas, rect.x + rect.width, rect.y);
        for (int x = 0; x < rect.width; ++x,
              ++src_color_ptr, --dst_color_ptr) {
            dst_color_ptr->value = src_color_ptr->value;
        }
    }
`

2021-09-28 02:53 UTC, lc-soft requested changes

2021-09-28 02:53 UTC, lc-soft commented on lib/platform/src/uwp/uwp_renderer.cpp
> +	ASSIGN(paint, pd_paint_context_t*);
改成 malloc() 调用。

2021-09-29 05:32 UTC, lc-soft approved these changes

2021-09-29 05:35 UTC, merged